#!/usr/bin/env node
/**
 * Walks a qa-audit results directory and builds a markdown report suitable
 * for posting as a GitHub Issue body.
 *
 * Usage:
 *   node aggregate-report.mjs <results-dir>
 *   node aggregate-report.mjs <results-dir> > report.md
 *
 * Output: markdown to stdout.
 */

import { readFileSync, readdirSync, existsSync } from 'fs';
import { join, basename } from 'path';

const resultsDir = process.argv[2];
if (!resultsDir || !existsSync(resultsDir)) {
    console.error('usage: aggregate-report.mjs <results-dir>');
    process.exit(1);
}

const summaryPath = join(resultsDir, 'SUMMARY.txt');
const summary = existsSync(summaryPath) ? readFileSync(summaryPath, 'utf8') : '';

function summaryField(name) {
    const m = summary.match(new RegExp('^' + name + ':\\s*(.+)$', 'm'));
    return m ? m[1].trim() : '';
}

const caasver = summaryField('caasver');
const baseUrl = summaryField('base_url');
const startedAt = summaryField('started');
const totalTime = summaryField('total');

const logs = readdirSync(resultsDir).filter((f) => f.endsWith('.log')).sort();

const scenarios = logs.map((filename) => {
    const path = join(resultsDir, filename);
    const text = readFileSync(path, 'utf8');
    const name = basename(filename, '.log');

    const verdictMatch = text.match(/\[(PASS|FAIL|FAIL_INCOMPLETE)\]/);
    const verdict = verdictMatch ? verdictMatch[1] : 'NO_VERDICT';

    const turnsCount = (text.match(/^Turn \d+/gm) || []).length;

    // The agent's final report is between the last two ====== separator lines.
    const SEP = '='.repeat(60);
    const parts = text.split(SEP);
    let longest = '';
    for (const p of parts) {
        if (p.length > longest.length) longest = p;
    }
    const report = longest.length > 50 ? longest.trim() : '(no report produced)';

    return { name, verdict, turnsCount, report };
});

const passCount = scenarios.filter((s) => s.verdict === 'PASS').length;
const failCount = scenarios.filter((s) => s.verdict === 'FAIL').length;
const incompleteCount = scenarios.filter((s) =>
    s.verdict === 'FAIL_INCOMPLETE' || s.verdict === 'NO_VERDICT',
).length;
const overall = (failCount > 0 || incompleteCount > 0) ? 'FAIL' : 'PASS';
const overallEmoji = overall === 'PASS' ? 'PASS' : 'FAIL';
const verdictTag = (v) =>
    v === 'PASS' ? 'PASS' :
    v === 'FAIL' ? 'FAIL' :
    v === 'FAIL_INCOMPLETE' ? 'INCOMPLETE' :
    'NO_VERDICT';

const lines = [];
lines.push(`# QA Audit Report - caasver=\`${caasver}\` - ${overallEmoji}`);
lines.push('');
lines.push(`- **Page tested:** \`${baseUrl}?caasver=${caasver}\``);
lines.push(`- **Started:** ${startedAt}`);
lines.push(`- **Total runtime:** ${totalTime}`);
lines.push(`- **Verdict:** ${overall} (${passCount} pass, ${failCount} fail, ${incompleteCount} incomplete)`);
lines.push('');
lines.push('## Summary');
lines.push('');
lines.push('| Scenario | Verdict | Turns |');
lines.push('|---|---|---|');
for (const s of scenarios) {
    lines.push(`| ${s.name} | ${verdictTag(s.verdict)} | ${s.turnsCount} |`);
}
lines.push('');
lines.push('## Findings detail');
lines.push('');
for (const s of scenarios) {
    lines.push(`<details><summary><strong>${s.name}</strong> - ${verdictTag(s.verdict)}</summary>`);
    lines.push('');
    lines.push('```');
    lines.push(s.report.slice(0, 8000));
    lines.push('```');
    lines.push('');
    lines.push('</details>');
    lines.push('');
}
lines.push('');
lines.push('<sub>Generated by `.github/workflows/qa-audit.yml`. Full per-scenario logs + screenshots are attached as workflow artifacts on the triggering run.</sub>');

console.log(lines.join('\n'));
