name: Build & commit dist on main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Commit updated dist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git log -1 --pretty=%B | grep -q "\[skip ci\]"; then
            exit 0
          fi
          git add dist
          if git diff --cached --quiet; then
            exit 0
          fi
          git commit -m "ci: rebuild dist on main [skip ci]"
          git push