name: Merge
on:
  push:
    branches:
    - 'main'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: write-all

jobs:
  run-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16.13.1
    - name: git config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - run: npm install
    - run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
