name: Publish dist to GitHub Release
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Zip dist folder
        run: zip -r dist.zip dist
      - name: Upload dist as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip