name: Test Tag Trigger

on:
  push:
    tags:
      - 'test-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo tag
        run: |
          echo "Tag was pushed: ${GITHUB_REF}"
          echo "This workflow was triggered!"
